#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return


export PATH=$PATH:$HOME/.local/bin
export PKG_CONFIG_PATH=/usr/local/lib/pkgconfig

alias ls='ls --color=auto'
PS1='\[\e[1;32m\][\u@\h \W]\$ \[\e[0m\]'
