[greeter]
background = /usr/share/backgrounds/xfce/traslasierra.jpg
theme-name = Greybird
icon-theme-name = elementary-xfce-darker
font-name = Roboto 11
indicators = ~host;~spacer;~session;~language;~a11y;~clock;~power
clock-format = %d %b, %H:%M

