[greeter]
background = /usr/share/backgrounds/xfce/xfce-blue.jpg
theme-name = Greybird
icon-theme-name = elementary-xfce-darker
font-name = Roboto 11
indicators = ~host;~spacer;~language;~session;~clock;~a11y;~power

