#
# ~/.bashrc
#

# If not running interactively, don't do anything
[[ $- != *i* ]] && return

_GREEN=$(tput setaf 2)
_RESET=$(tput sgr0)
_BOLD=$(tput bold)

alias ls='ls --color=auto'
PS1='\[${_BOLD}${_GREEN}\][\u@\h \W]\$ \[${_RESET}\]'
